In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv('NYC EH Data Portal - Asthma emergency department visits due to PM2.5 (filtered).csv')
data

,TimePeriod,GeoTypeDesc,GeoID,GeoRank,BoroID,Borough,Geography,Area,Estimated annual number (under age 18),Estimated annual number (age 18+),"Estimated annual rate (under age 18) per 100,000 children","Estimated annual rate (age 18+) per 100,000 adults"
0,2005-2007,Citywide,1,0,-,-,New York City,New York City,"2,423.9","3,581.3",126.3,56.9
1,2005-2007,Borough,1,1,1,Bronx,Bronx,Bronx,832.4,"1,183.2",212.5,122.3
2,2005-2007,Borough,3,1,3,Manhattan,Manhattan,Manhattan,485.5,797.5,179.4,59.9
3,2005-2007,Borough,2,1,2,Brooklyn,Brooklyn,Brooklyn,642.2,"1,032.4",99.3,55.5
4,2005-2007,Borough,5,1,5,Staten Island,Staten Island,Staten Island,63.1,106.8,55.3,29.6
5,2005-2007,Borough,4,1,4,Queens,Queens,Queens,400.8,461.4,80.8,26.0
6,2005-2007,UHF 42,101,4,1,Bronx,Kingsbridge - Riverdale,Kingsbridge - Riverdale Bronx,15.5,24.9,-,-
7,2005-2007,UHF 42,102,4,1,Bronx,Northeast Bronx,Northeast Bronx Bronx,70.1,97.5,-,-
8,2005-2007,UHF 42,103,4,1,Bronx,Fordham - Bronx Pk,Fordham - Bronx Pk Bronx,126.1,194.2,-,-
9,2005-2007,UHF 42,104,4,1,Bronx,Pelham - Throgs Neck,Pelham - Throgs Neck Bronx,123.4,173.5,-,-
10,2005-2007,UHF 42,105,4,1,Bronx,Crotona - Tremont,Crotona - Tremont Bronx,177.7,266.0,-,-
11,2005-2007,UHF 42,106,4,1,Bronx,High Bridge - Morrisania,High Bridge - Morrisania Bronx,200.6,260.3,-,-
12,2005-2007,UHF 42,107,4,1,Bronx,Hunts Point - Mott Haven,Hunts Point - Mott Haven Bronx,119.0,166.9,-,-
13,2005-2007,UHF 42,201,4,2,Brooklyn,Greenpoint,Greenpoint Brooklyn,22.5,33.5,-,-
14,2005-2007,UHF 42,202,4,2,Brooklyn,Downtown - Heights - Slope,Downtown - Heights - Slope Brooklyn,41.5,107.5,-,-
15,2005-2007,UHF 42,203,4,2,Brooklyn,Bedford Stuyvesant - Crown Heights,Bedford Stuyvesant - Crown Heights Brooklyn,170.6,259.3,-,-
16,2005-2007,UHF 42,204,4,2,Brooklyn,East New York,East New York Brooklyn,96.5,121.9,-,-
17,2005-2007,UHF 42,205,4,2,Brooklyn,Sunset Park,Sunset Park Brooklyn,15.0,43.9,-,-
18,2005-2007,UHF 42,206,4,2,Brooklyn,Borough Park,Borough Park Brooklyn,14.3,31.0,-,-
19,2005-2007,UHF 42,207,4,2,Brooklyn,East Flatbush - Flatbush,East Flatbush - Flatbush Brooklyn,91.1,130.8,-,-
20,2005-2007,UHF 42,208,4,2,Brooklyn,Canarsie - Flatlands,Canarsie - Flatlands Brooklyn,45.3,62.2,-,-
21,2005-2007,UHF 42,209,4,2,Brooklyn,Bensonhurst - Bay Ridge,Bensonhurst - Bay Ridge Brooklyn,7.9,23.9,-,-
22,2005-2007,UHF 42,210,4,2,Brooklyn,Coney Island - Sheepshead Bay,Coney Island - Sheepshead Bay Brooklyn,25.0,55.8,-,-
23,2005-2007,UHF 42,211,4,2,Brooklyn,Williamsburg - Bushwick,Williamsburg - Bushwick Brooklyn,112.6,162.7,-,-
24,2005-2007,UHF 42,301,4,3,Manhattan,Washington Heights,Washington Heights Manhattan,111.3,132.9,-,-
25,2005-2007,UHF 42,302,4,3,Manhattan,Central Harlem - Morningside Heights,Central Harlem - Morningside Heights Manhattan,149.6,230.5,-,-
26,2005-2007,UHF 42,303,4,3,Manhattan,East Harlem,East Harlem Manhattan,98.3,161.8,-,-
27,2005-2007,UHF 42,304,4,3,Manhattan,Upper West Side,Upper West Side Manhattan,40.7,65.4,-,-
28,2005-2007,UHF 42,305,4,3,Manhattan,Upper East Side,Upper East Side Manhattan,14.0,23.3,-,-
29,2005-2007,UHF 42,306,4,3,Manhattan,Chelsea - Clinton,Chelsea - Clinton Manhattan,17.0,48.0,-,-
30,2005-2007,UHF 42,307,4,3,Manhattan,Gramercy Park - Murray Hill,Gramercy Park - Murray Hill Manhattan,7.0,33.1,-,-
31,2005-2007,UHF 42,308,4,3,Manhattan,Greenwich Village - SoHo,Greenwich Village - SoHo Manhattan,2.8,9.3,-,-
32,2005-2007,UHF 42,309,4,3,Manhattan,Union Square - Lower East Side,Union Square - Lower East Side Manhattan,41.2,82.7,-,-
33,2005-2007,UHF 42,310,4,3,Manhattan,Lower Manhattan,Lower Manhattan Manhattan,3.6,10.4,-,-
34,2005-2007,UHF 42,401,4,4,Queens,Long Island City - Astoria,Long Island City - Astoria Queens,30.1,32.1,-,-
35,2005-2007,UHF 42,402,4,4,Queens,West Queens,West Queens Queens,94.2,86.3,-,-
36,2005-2007,UHF 42,403,4,4,Queens,Flushing - Clearview,Flushing - Clearview Queens,25.1,28.7,-,-
37,2005-2007,UHF 42,404,4,4,Queens,Bayside - Little Neck,Bayside - Little Neck Queens,4.7,6.0,-,-
38,2005-2007,UHF 42,405,4,4,Queens,Ridgewood - Forest Hills,Ridgewood - Forest Hills Queens,24.0,35.8,-,-
39,2005-2007,UHF 42,406,4,4,Queens,Fresh Meadows,Fresh Meadows Queens,11.4,16.0,-,-
40,2005-2007,UHF 42,407,4,4,Queens,Southwest Queens,Southwest Queens Queens,54.3,62.5,-,-
41,2005-2007,UHF 42,408,4,4,Queens,Jamaica,Jamaica Queens,78.4,103.7,-,-
42,2005-2007,UHF 42,409,4,4,Queens,Southeast Queens,Southeast Queens Queens,34.3,43.7,-,-
43,2005-2007,UHF 42,410,4,4,Queens,Rockaways,Rockaways Queens,44.4,46.7,-,-
44,2005-2007,UHF 42,501,4,5,Staten Island,Port Richmond,Port Richmond Staten Island,21.9,31.6,-,-
45,2005-2007,UHF 42,502,4,5,Staten Island,Stapleton - St. George,Stapleton - St. George Staten Island,24.7,40.4,-,-
46,2005-2007,UHF 42,503,4,5,Staten Island,Willowbrook,Willowbrook Staten Island,5.9,11.2,-,-
47,2005-2007,UHF 42,504,4,5,Staten Island,South Beach - Tottenville,South Beach - Tottenville Staten Island,10.6,23.6,-,-

In [3]:
# Create the new table with a descriptive name
asthma_rates_by_borough = data[['TimePeriod', 'Borough'] + list(data.columns[-4:])].copy()

# View the new table
asthma_rates_by_borough.head()

,TimePeriod,Borough,Estimated annual number (under age 18),Estimated annual number (age 18+),"Estimated annual rate (under age 18) per 100,000 children","Estimated annual rate (age 18+) per 100,000 adults"
0,2005-2007,-,"2,423.9","3,581.3",126.3,56.9
1,2005-2007,Bronx,832.4,"1,183.2",212.5,122.3
2,2005-2007,Manhattan,485.5,797.5,179.4,59.9
3,2005-2007,Brooklyn,642.2,"1,032.4",99.3,55.5
4,2005-2007,Staten Island,63.1,106.8,55.3,29.6